# Project information
site_name: Kevlar
site_url: https://kevlar-kt.github.io/kevlar
site_author: Kevlar
site_description: >-
    Android Security Toolkit

repo_name: kevlar
repo_url: https://github.com/kevlar-kt/kevlar
remote_branch: gh-pages
edit_uri: ""


theme:
    name: material
    language: en

    logo: assets/images/shield_light.png
    favicon: assets/images/shield_light.png

    features:
        - content.code.annotate
        # - content.tabs.link
        # - header.autohide
        - navigation.instant
        # - navigation.expand
        - navigation.sections
        - navigation.tabs
        - navigation.indexes
        # - navigation.tabs.sticky
        # - navigation.tracking
        - navigation.indexes
        - search.highlight
        - search.share
        - search.suggest
        # - toc.integrate

    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: cyan
          accent: orange
          toggle:
              icon: material/lightbulb-outline
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: cyan
          accent: orange
          toggle:
              icon: material/lightbulb
              name: Switch to light mode


plugins:
    - search:
          lang: en
    - redirects:
          redirect_maps:
    - minify:
          minify_html: true


nav:
    - 'Index':
          - 'Overview': index.md
          - 'Dependencies & Integration': pages/overview/dependencies_integration.md
          # - 'Choosing Packages': pages/overview/choosing.md
          - 'Anatomy of an Attack': pages/overview/anatomy_of_attacks.md
          - 'Philosophy': pages/overview/philosophy.md
          - 'Attitude': pages/overview/attitude.md
          - 'Technical Material': pages/overview/material.md
    - Antipiracy:
          - 'Overview' : pages/modules/antipiracy/antipiracy.md
          - 'Reference' : pages/modules/antipiracy/reference.md
          - 'Implementation' : pages/modules/antipiracy/implementation.md
          - 'Detection' : pages/modules/antipiracy/detection.md
          - 'Database' : pages/modules/antipiracy/database.md
          - 'Privacy & Permissions' : pages/modules/antipiracy/privacy.md
          - 'Tradeoffs' : pages/modules/antipiracy/tradeoffs.md
    - 'Rooting':
          - 'Overview' : pages/modules/rooting/rooting.md
          - 'Implementation' : pages/modules/rooting/implementation.md
          - 'Internals' : pages/modules/rooting/internals.md
    - 'Integrity':
          - 'Overview': pages/modules/integrity/integrity.md
          - 'Reference': pages/modules/integrity/reference.md
          - 'Implementation': pages/modules/integrity/implementation.md
          - 'Hardcoding': pages/modules/integrity/hardcoding.md

markdown_extensions:
    - tables
    - footnotes
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.details
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - abbr
    - admonition
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - def_list
    - md_in_html
    - toc:
          permalink: true

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/kevlar-kt

        - icon: fontawesome/brands/twitter
          link: https://twitter.com/cioccarellia

extra_css:
    - 'assets/css/app.css'
    - 'assets/css/extra.css'
