# Project information
site_name: Kevlar
site_url: https://kevlar-kt.github.io/kevlar
site_author: Kevlar
site_description: >-
    Android Security Framework

repo_name: Kevlar
repo_url: https://github.com/kevlar-kt/kevlar
remote_branch: gh-pages
edit_uri: ""


theme:
    name: material
    language: en
    logo: assets/images/shield_light.png
    favicon: assets/images/shield_light.png

    features:
        - content.code.annotate
        # - content.tabs.link
        # - header.autohide
        # - navigation.expand
        - navigation.instant
        # - navigation.instant
        - navigation.sections
        - navigation.tabs
        # - navigation.tabs.sticky
        - navigation.tracking
        - navigation.indexes
        - search.highlight
        - search.share
        - search.suggest
        # - toc.integrate
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: cyan
          accent: orange
          toggle:
              icon: material/lightbulb-outline
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: cyan
          accent: orange
          toggle:
              icon: material/lightbulb
              name: Switch to light mode

extra_css:
  - 'assets/css/app.css'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kevlar-kt

    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/cioccarellia

markdown_extensions:
    - tables
    - footnotes
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - abbr
    - admonition
    - attr_list
    - def_list
    - md_in_html

nav:
    - 'Overview':
        - 'Overview': index.md
    - 'Modules':
         - 'Antipiracy': modules/antipiracy.md
         - 'Integrity': modules/integrity.md
         - 'Rooting': modules/rooting.md